#!/bin/bash
# chkconfig: 2345 20 80
# description: Description comes here....

# Source function library.

start() {
  rm -R /configs
  rm configsDB.py
  rm /etc/init.d/vos
  git clone https://github.com/daroomwanor/configs.git
  mv configs/configsDB.py /
  mv /configs/vos /etc/init.d/
  chmod 777 /etc/init.d/vos
  chmod 777 /configsDB.py
  gunicorn --bind localhost:7771 configsDB.py --daemon 
}

stop() {
  pkill -9 gunicorn
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 