#!/bin/bash
# chkconfig: 2345 20 80
# description: Description comes here....

# Source function library.

start() {
  rm -R /configs
  rm configsDB.py
  rm /etc/init.d/vos
  git clone https://github.com/daroomwanor/configs.git
  mv configs/configsDB.py /
  mv /configs/vos /etc/init.d/
  chmod 777 /etc/init.d/vos
  chmod 777 /configsDB.py
  gunicorn --bind localhost:7771 configsDB.py --daemon 
}

stop() {
  pkill -9 gunicorn
}

start_ngrok() {
  pkill -9 ngrok
  rm -R ngrok
  rm ngrok.zip
  curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  unzip ngrok.zip
  /ngrok http 8888
}

stop_ngrok() {
  pkill -9 ngrok
}

start_notebook() {
  pkill -9 jupyter
  jupyter notebook --allow-root --NotebookApp.allow_remote_access=True --NotebookApp.token="" --NotebookApp.password=""&
}

stop_notebook() {
  pkill -9 jupyter
}
case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    start_ngrok)
      start_ngrok
       ;;
    stop_ngrok)
      stop_ngrok
       ;;
    start_notebook)
      start_notebook
       ;;
    stop_notebook)
      stop_notebook
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 